Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.transfer_data() running at /root/anaconda3/envs/okex/lib/python3.7/site-packages/websockets/protocol.py:838> wait_for=<Future pending cb=[shield.<locals>._outer_done_callback() at /root/anaconda3/envs/okex/lib/python3.7/asyncio/tasks.py:820, <TaskWakeupMethWrapper object at 0x7f41aa0b7550>()]> cb=[<TaskWakeupMethWrapper object at 0x7f41a05f8050>()]>
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.close_connection() running at /root/anaconda3/envs/okex/lib/python3.7/site-packages/websockets/protocol.py:1169> wait_for=<Task pending coro=<WebSocketCommonProtocol.transfer_data() running at /root/anaconda3/envs/okex/lib/python3.7/site-packages/websockets/protocol.py:838> wait_for=<Future pending cb=[shield.<locals>._outer_done_callback() at /root/anaconda3/envs/okex/lib/python3.7/asyncio/tasks.py:820, <TaskWakeupMethWrapper object at 0x7f41aa0b7550>()]> cb=[<TaskWakeupMethWrapper object at 0x7f41a05f8050>()]>>
